Initial version of the role
stuvusIT/ansible_keepalived pull request #1
Opened 2020-09-21 01:14 UTC by haslersn

2020-09-21 20:29 UTC, neumantm requested changes

2020-09-21 20:29 UTC, neumantm commented on README.md
> +[Ubuntu](https://www.ubuntu.com/) or [Debian](https://www.debian.org/).
Are you sure Ubuntu is supported?

2020-09-21 20:52 UTC, haslersn commented on README.md
> +[Ubuntu](https://www.ubuntu.com/) or [Debian](https://www.debian.org/).
No. So I changed that line.

2020-09-22 16:38 UTC, neumantm approved these changes

2020-09-22 19:13 UTC, merged